### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by acolombo1** [rbanos-mv/capstone-4-catalog#26]
Dear reviewer, we are 3 people in our team:
Team member #1: @jrosario19
Team member #2: @rbanos-mv
Team member #3: @acolombo1

This is the link to our Github project:
https://github.com/rbanos-mv/capstone-4-catalog/projects/1

So we did the following:

Join a Zoom call with our team. Only one person needs to copy the board on behalf of the entire team but everybody helps during the call.
- Create an empty repository for your group project.
- Copy the [[TEMPLATE] Ruby Group Capstone Project](https://github.com/microverseinc/curriculum-ruby/projects/1) board.
- Open the GitHub project (Kanban board) in your team repo.
- Open [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things.md) and read them carefully.
- Open [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) and compare it with the [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things.md).
- Create tasks on your Kanban board based on the [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md).
- Each task should be a separate card that:
  - Has a descriptive title.
  - Has the number of points in the [Xpt] prefix. 1 point = 1 hour of estimated work.
  - Has a description of the task.
  - Each of the team members should assign themselves to the cards as divided in the [project requirements divided by team member] 
  - All cards on your Kanban board should have assignees.

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi team,  

Your project is complete! Great job for nailing it right on the first attempt 🥇.


![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
